spring.datasource.url=jdbc:mysql://localhost:3306/craftsdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=K0mT3yM2+pE+F1+nZdV6UOhZoDjMfLuER8A7rFxq7sFUm+EjEo3kJp+B3Zx0w0YLCMPdEMQ3GhuXRq+ulGehsw==

